# Generated by Django 5.2.7 on 2025-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
